// client-ng/src/app/side-bar/side-bar.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { HomeDto } from '../home';

@Component({
  selector: 'app-side-bar',
  templateUrl: './side-bar.component.html',
  styleUrls: ['./side-bar.component.scss']
})
export class SideBarComponent implements OnInit {
  @Input() links !: HomeDto;

  constructor() { }

  ngOnInit(): void {
  }

}

<div>
    <span class="logo">K</span>
</div>
<nav>
    <app-note-button [routerLink]="links.learning.rel" className="fas fa-graduation-cap fa-fw fa-2x">
        {{ links.learning.title }}
    </app-note-button>

    <app-note-button [routerLink]="links.hours.rel" className="fas fa-calendar-alt fa-fw fa-2x">
        {{ links.hours.title }}
    </app-note-button>

    <app-note-button [routerLink]="links.todos.rel" className="fas fa-clipboard-list fa-fw fa-2x">
        {{ links.todos.title }}
    </app-note-button>
</nav>

// client-vue3/src/side-bar/side-bar.vue
<template>
  <div>
    <span class="logo">K</span>
  </div>
  <nav>
    <category-button :routerLink="navigation.learning.rel" icon="graduation-cap">
      {{ navigation.learning.title }}
    </category-button>
    <category-button :routerLink="navigation.hours.rel" icon="calendar-alt">
      {{ navigation.hours.title }}
    </category-button>
    <category-button :routerLink="navigation.todos.rel" icon="clipboard-list">
      {{ navigation.todos.title }}
    </category-button>
  </nav>
</template>
<script lang="ts">
  import { defineComponent } from 'vue';
  import CategoryButton from './category-button.vue';
  import { HomeDto } from './home';
  export default defineComponent({
    name: 'SideBar',
    components: {
      CategoryButton
    },
    created() {
      this.navigation = {
        href: '/',
        rel: '/',
        learning: {
          href: '/learning',
          rel: '/learning',
          title: 'Learning'
        },
        hours: {
          href: '/hours',
          rel: '/hours',
          title: 'Hours'
        },
        todos: {
          href: '/todos',
          rel: '/todos',
          title: 'Todos'
        }
      } as HomeDto;
    },
    data() {
      return {
        navigation: {} as HomeDto
      };
    }
  });
</script>
<style lang="css">
  .logo {
    display: block;
    text-align: center;
    font-size: xx-large;
    padding-top: 20px;
    padding-bottom: 20px;
  }
</style>
